// <auto-generated />
namespace MVCWebAPITutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedclassandcontoller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedclassandcontoller));
        
        string IMigrationMetadata.Id
        {
            get { return "201806212013480_added class and contoller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
